
install:
	pip install gds3xtrude --upgrade

example:
	gds3xtrude --tech freepdk45.layerstack --input gds/NAND2X1.gds --view

generic:
	gds3xtrude --tech generic.layerstack --input mzi.gds --view

logo:
	gds3xtrude --tech generic.layerstack --input gds/logo.gds --view
