FROM jupyter/base-notebook:python-3.10
# FROM jupyter/base-notebook
# FROM continuumio/miniconda3

# expose klive and Jupyter Notebook ports
EXPOSE 8082
EXPOSE 8083
EXPOSE 8888

USER root
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
        make \
        git \
        python3-gmsh \
        htop \
        neovim \
        software-properties-common \
        gnupg && \
    apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa && \
    apt-get update --yes && \
    apt-get install --yes elmerfem-csc && \
    rm -rf /var/lib/apt/lists/*  # Undo apt-get update for final image

USER jovyan
# COPY . /home/jovyan/gdfactory
# COPY --chown=jovyan docs/notebooks /home/jovyan/notebooks
# COPY docs/notebooks/00__git.ipynb /home/jovyan/
RUN conda init bash

# RUN git clone https://github.com/gdsfactory/gdsfactory.git
# USER ${NB_UID}
# RUN apt update
# RUN apt install gcc
# RUN conda install -c conda-forge pymeep -y

RUN mamba install gdspy gdstk pymeep=*=mpi_mpich_* -y && \
    mamba install -c conda-forge slepc4py=*=complex* -y


RUN pip install gdsfactory[cad] gplugins[database,devsim,femwell,gmsh,meow,meshwell,ray,sax,schematic,tidy3d,web]
WORKDIR /home/jovyan
# VOLUME /home/jovyan/work
