"""Component functions: undecorated builders behind ``gdsfactory.components``.

Each function here returns a new ``Component`` and is not cached. The cells in
``gdsfactory.components`` wrap them with ``@gf.cell``. A PDK can wrap them with
its own cell decorator instead.

Component functions look up sub-cells by name in the active PDK through
``get_component``, so PDK overrides apply inside composite components.
"""

from . import (
    bends,
    detectors,
    edge_couplers,
    mems,
    microfluidics,
    mmis,
    mzis,
    pads,
    shapes,
    superconductors,
    tapers,
    texts,
    waveguides,
)
from ._get_component import ComponentFallbackWarning, get_component
from .bends import *
from .detectors import *
from .edge_couplers import *
from .mems import *
from .microfluidics import *
from .mmis import *
from .mzis import *
from .pads import *
from .shapes import *
from .superconductors import *
from .tapers import *
from .texts import *
from .waveguides import *

__all__ = [
    "C",
    "ComponentFallbackWarning",
    "L",
    "anchored_flexure",
    "arrow_junction",
    "bbox",
    "bend_circular",
    "bend_circular_all_angle",
    "bend_circular_heater",
    "bend_euler",
    "bend_euler_all_angle",
    "bend_euler_s",
    "bend_modified_hermite",
    "bend_modified_hermite_all_angle",
    "bend_modified_hermite_s",
    "bend_s",
    "bend_s_offset",
    "bend_topic",
    "bend_topic_all_angle",
    "bend_topic_s",
    "bends",
    "bent_beam",
    "bezier",
    "bolometer",
    "bump_pad",
    "bump_pad_grid",
    "cantilever",
    "circle",
    "circle_wave",
    "comb_drive",
    "compass",
    "cross",
    "crossing",
    "crossing45",
    "crossing_arm",
    "crossing_etched",
    "crossing_linear_taper",
    "dash",
    "detectors",
    "doubly_clamped_beam",
    "edge_coupler_array",
    "edge_coupler_array_with_loopback",
    "edge_coupler_silicon",
    "edge_couplers",
    "ellipse",
    "fiducial_squares",
    "folded_spring",
    "fractal",
    "ge_detector_straight_si_contacts",
    "gear",
    "get_component",
    "h_junction",
    "hline",
    "meander_channel",
    "mems",
    "microfluidics",
    "mmi",
    "mmi1x2",
    "mmi1x2_with_sbend",
    "mmi2x2",
    "mmi2x2_with_sbend",
    "mmi_90degree_hybrid",
    "mmi_tapered",
    "mmis",
    "mzi",
    "mzi_lattice",
    "mzi_lattice_mmi",
    "mzi_pads_center",
    "mzis",
    "mzit",
    "mzit_lattice",
    "nxn",
    "optimal_90deg",
    "optimal_hairpin",
    "optimal_step",
    "pad",
    "pad_array",
    "pad_gs",
    "pad_gsg",
    "pad_gsg_short",
    "pads",
    "pads_shorted",
    "pie_arc",
    "pixel_array",
    "ramp",
    "rect_su_shape",
    "rect_taper",
    "rectangle",
    "rectangle_with_slits",
    "rectangles",
    "regular_polygon",
    "rounded_rectangle",
    "shapes",
    "snspd",
    "star",
    "straight",
    "straight_all_angle",
    "straight_array",
    "straight_heater_doped_rib",
    "straight_heater_doped_strip",
    "straight_heater_meander",
    "straight_heater_meander_doped",
    "straight_heater_metal_simple",
    "straight_heater_metal_undercut",
    "straight_piecewise",
    "straight_pin",
    "straight_pin_slot",
    "superconductors",
    "t_junction",
    "taper",
    "taper_adiabatic",
    "taper_cross_section",
    "taper_from_csv",
    "taper_hecken",
    "taper_meander",
    "taper_nc_sc",
    "taper_parabolic",
    "taper_sc_nc",
    "taper_strip_to_ridge",
    "taper_strip_to_ridge_trenches",
    "tapers",
    "text",
    "text_freetype",
    "text_klayout",
    "text_lines",
    "text_rectangular",
    "text_rectangular_multi_layer",
    "texts",
    "torus",
    "torus_wave",
    "triangle",
    "triangle2",
    "triangle4",
    "waveguides",
    "wire_corner",
    "wire_corner45",
    "wire_corner45_straight",
    "wire_corner_sections",
    "wire_straight",
    "ytron_round",
]
