"""Component functions: undecorated builders behind ``gdsfactory.components``.

Each function here returns a new ``Component`` and is not cached. The cells in
``gdsfactory.components`` wrap them with ``@gf.cell``. A PDK can wrap them with
its own cell decorator instead.

Component functions look up sub-cells by name in the active PDK through
``get_component``, so PDK overrides apply inside composite components.
"""

from . import (
    analog,
    bends,
    containers,
    couplers,
    detectors,
    dies,
    edge_couplers,
    filters,
    grating_couplers,
    mems,
    microfluidics,
    mmis,
    mzis,
    pads,
    pcms,
    quantum,
    rings,
    shapes,
    spirals,
    superconductors,
    tapers,
    texts,
    vias,
    waveguides,
)
from ._alias import CellAlias
from ._get_component import ComponentFallbackWarning, get_component
from .analog import *
from .bends import *
from .containers import *
from .couplers import *
from .detectors import *
from .dies import *
from .edge_couplers import *
from .filters import *
from .grating_couplers import *
from .mems import *
from .microfluidics import *
from .mmis import *
from .mzis import *
from .pads import *
from .pcms import *
from .quantum import *
from .rings import *
from .shapes import *
from .spirals import *
from .superconductors import *
from .tapers import *
from .texts import *
from .vias import *
from .waveguides import *

__all__ = [
    "C",
    "CellAlias",
    "ComponentFallbackWarning",
    "L",
    "add_fiber_array_optical_south_electrical_north",
    "add_frame",
    "add_termination",
    "add_trenches",
    "align_wafer",
    "alignment_mark_cross",
    "analog",
    "anchored_flexure",
    "array",
    "array_hexagonal",
    "array_polar",
    "arrow_junction",
    "awg",
    "bbox",
    "bend_circular",
    "bend_circular_all_angle",
    "bend_circular_heater",
    "bend_euler",
    "bend_euler_all_angle",
    "bend_euler_s",
    "bend_modified_hermite",
    "bend_modified_hermite_all_angle",
    "bend_modified_hermite_s",
    "bend_s",
    "bend_s_offset",
    "bend_topic",
    "bend_topic_all_angle",
    "bend_topic_s",
    "bends",
    "bendu_double",
    "bent_beam",
    "bezier",
    "bolometer",
    "bump_pad",
    "bump_pad_grid",
    "cantilever",
    "cavity",
    "cdsem_all",
    "cdsem_bend180",
    "cdsem_coupler",
    "cdsem_straight",
    "cdsem_straight_density",
    "circle",
    "circle_wave",
    "comb_drive",
    "compass",
    "containers",
    "copy_layers",
    "coupler",
    "coupler90",
    "coupler90bend",
    "coupler_adiabatic",
    "coupler_asymmetric",
    "coupler_bend",
    "coupler_bent",
    "coupler_bent_half",
    "coupler_broadband",
    "coupler_capacitive",
    "coupler_full",
    "coupler_interdigital",
    "coupler_pulley",
    "coupler_ring",
    "coupler_ring_bend",
    "coupler_straight",
    "coupler_straight_asymmetric",
    "coupler_symmetric",
    "coupler_tunable",
    "couplers",
    "cross",
    "crossing",
    "crossing45",
    "crossing_arm",
    "crossing_etched",
    "crossing_linear_taper",
    "cutback_2x2",
    "cutback_bend",
    "cutback_bend90",
    "cutback_bend180",
    "cutback_component",
    "cutback_splitter",
    "dash",
    "dbr",
    "dbr_cell",
    "dbr_tapered",
    "delay_snake",
    "delay_snake2",
    "delay_snake_sbend",
    "detectors",
    "die",
    "die_frame",
    "die_frame_phix",
    "die_frame_phix_dc",
    "die_frame_phix_rf",
    "die_frame_rf",
    "die_frame_with_pads",
    "die_with_pads",
    "dies",
    "disk",
    "disk_heater",
    "doubly_clamped_beam",
    "edge_coupler_array",
    "edge_coupler_array_with_loopback",
    "edge_coupler_silicon",
    "edge_couplers",
    "ellipse",
    "extend_ports",
    "extend_ports_list",
    "fiber",
    "fiber_array",
    "fiducial_squares",
    "filters",
    "flux_qubit",
    "flux_qubit_asymmetric",
    "folded_spring",
    "fractal",
    "free_propagation_region",
    "ge_detector_straight_si_contacts",
    "gear",
    "get_component",
    "grating_coupler_array",
    "grating_coupler_dual_pol",
    "grating_coupler_elliptical",
    "grating_coupler_elliptical_arbitrary",
    "grating_coupler_elliptical_lumerical",
    "grating_coupler_elliptical_trenches",
    "grating_coupler_elliptical_uniform",
    "grating_coupler_loss",
    "grating_coupler_rectangular",
    "grating_coupler_rectangular_arbitrary",
    "grating_coupler_tree",
    "grating_couplers",
    "greek_cross",
    "greek_cross_with_pads",
    "h_junction",
    "hline",
    "inductor",
    "interdigital_capacitor",
    "interdigitated_electrodes",
    "litho_calipers",
    "litho_ruler",
    "litho_steps",
    "loop_mirror",
    "meander_channel",
    "mems",
    "microfluidics",
    "mmi",
    "mmi1x2",
    "mmi1x2_with_sbend",
    "mmi2x2",
    "mmi2x2_with_sbend",
    "mmi_90degree_hybrid",
    "mmi_tapered",
    "mmis",
    "mode_converter",
    "mzi",
    "mzi_lattice",
    "mzi_lattice_mmi",
    "mzi_pads_center",
    "mzis",
    "mzit",
    "mzit_lattice",
    "nxn",
    "optimal_90deg",
    "optimal_hairpin",
    "optimal_step",
    "pack_doe",
    "pack_doe_grid",
    "pad",
    "pad_array",
    "pad_gs",
    "pad_gsg",
    "pad_gsg_short",
    "pads",
    "pads_shorted",
    "pcms",
    "pie_arc",
    "pixel",
    "pixel_array",
    "polarization_splitter_rotator",
    "qrcode",
    "quantum",
    "ramp",
    "rect_su_shape",
    "rect_taper",
    "rectangle",
    "rectangle_with_slits",
    "rectangles",
    "regular_polygon",
    "resistance_meander",
    "resistance_meander_net",
    "resistance_meander_row",
    "resistance_sheet",
    "resolution_test_pattern",
    "resonator_cpw",
    "resonator_lumped",
    "resonator_quarter_wave",
    "ring",
    "ring_asymmetric",
    "ring_crow",
    "ring_crow_couplers",
    "ring_double",
    "ring_double_bend_coupler",
    "ring_double_heater",
    "ring_double_pn",
    "ring_single",
    "ring_single_array",
    "ring_single_bend_coupler",
    "ring_single_dut",
    "ring_single_pn",
    "rings",
    "rounded_rectangle",
    "ruler",
    "seal_ring",
    "seal_ring_segmented",
    "shapes",
    "snspd",
    "spiral",
    "spiral_archimedes",
    "spiral_double",
    "spiral_fermat",
    "spiral_inductor",
    "spiral_logarithmic",
    "spiral_racetrack",
    "spiral_racetrack_fixed_length",
    "spiral_racetrack_heater_doped",
    "spiral_racetrack_heater_metal",
    "spiral_rectangular",
    "spirals",
    "splitter_chain",
    "splitter_tree",
    "stacked_transformer",
    "staircase",
    "star",
    "straight",
    "straight_all_angle",
    "straight_array",
    "straight_double",
    "straight_heater_doped_rib",
    "straight_heater_doped_strip",
    "straight_heater_meander",
    "straight_heater_meander_doped",
    "straight_heater_metal_simple",
    "straight_heater_metal_undercut",
    "straight_piecewise",
    "straight_pin",
    "straight_pin_slot",
    "superconductors",
    "symmetric_transformer",
    "t_junction",
    "taper",
    "taper_adiabatic",
    "taper_cross_section",
    "taper_from_csv",
    "taper_hecken",
    "taper_meander",
    "taper_nc_sc",
    "taper_parabolic",
    "taper_sc_nc",
    "taper_strip_to_ridge",
    "taper_strip_to_ridge_trenches",
    "tapers",
    "terminator",
    "terminator_spiral",
    "text",
    "text_freetype",
    "text_klayout",
    "text_lines",
    "text_rectangular",
    "text_rectangular_multi_layer",
    "texts",
    "torus",
    "torus_wave",
    "transformer_concentric_secondary",
    "transmon",
    "transmon_circular",
    "triangle",
    "triangle2",
    "triangle4",
    "vernier_scale",
    "verniers",
    "version_stamp",
    "via",
    "via3",
    "via_chain",
    "via_circular",
    "via_corner",
    "via_stack",
    "via_stack_corner45",
    "via_stack_corner45_extended",
    "via_stack_with_offset",
    "vias",
    "wafer",
    "waveguides",
    "wire_corner",
    "wire_corner45",
    "wire_corner45_straight",
    "wire_corner_sections",
    "wire_straight",
    "ytron_round",
]
